name: Quibble

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install quibble
        run: docker pull docker-registry.wikimedia.org/releng/quibble-buster-php74:latest
      - name: initialize bare git repos
        run: |
          mkdir -p ref/mediawiki/skins
          git clone --bare --depth 1 https://gerrit.wikimedia.org/r/mediawiki/core ref/mediawiki/core.git
          git clone --bare --depth 1 https://gerrit.wikimedia.org/r/mediawiki/vendor ref/mediawiki/vendor.git
          git clone --bare --depth 1 https://gerrit.wikimedia.org/r/mediawiki/skins/Vector ref/mediawiki/skins/Vector.git
      - name: Setup directories and permissions
        run: |
          mkdir cache
          chmod 777 cache
          mkdir -p log
          chmod 777 log
          mkdir -p src
          chmod 777 src
      - name: Run MediaWiki Docker container
        run: |
          docker run -i --rm \
            -v "$(pwd)"/cache:/cache \
            -v "$(pwd)"/log:/workspace/log \
            -v "$(pwd)"/ref:/srv/git:ro \
            -v "$(pwd)"/src:/workspace/src \
            docker-registry.wikimedia.org/releng/quibble-buster-php74:latest
